// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YB_MelihEfeOmer_RezervasyonApp.DataAccess.Context;

#nullable disable

namespace YB_MelihEfeOmer_RezervasyonApp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240726082642_dataAddingFixed")]
    partial class dataAddingFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.BRBookingGuest", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId", "GuestId");

                    b.HasIndex("GuestId");

                    b.ToTable("BRBookingGuests");

                    b.HasData(
                        new
                        {
                            BookingId = new Guid("b88f4b65-c8da-46d5-b02e-156e2170a834"),
                            GuestId = new Guid("4cb35a91-9175-4731-98c4-ace3a91f5643"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9467),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("088b1f41-b184-4ea5-aad5-c0031b4059bb"),
                            GuestId = new Guid("b7123bd7-dcfd-480b-af66-8a0449e5091e"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9468),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("4fb82c6d-fca5-4de7-9245-a3c348e2a219"),
                            GuestId = new Guid("1e587ae7-13be-49c9-aa52-6a21f8778102"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9470),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("13c1556d-411e-4a5f-8bea-fa15646dbbf1"),
                            GuestId = new Guid("ac616ce8-f79f-499b-8538-90ae2245c480"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9472),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("b0a4ccdb-c3ea-4267-b038-794f758d0efb"),
                            GuestId = new Guid("86806108-b61b-4ace-90a4-3022a65b4ed0"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9473),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("016672c1-6f7a-4673-b739-5805ce970d89"),
                            GuestId = new Guid("295e1506-5428-4fb9-8805-061aced2e2b0"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9473),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("41bdb9ac-86cf-4d52-beb3-690f98ec123b"),
                            GuestId = new Guid("ad2493d2-3fdc-44b0-a867-21d8592045b7"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9474),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("088b1f41-b184-4ea5-aad5-c0031b4059bb"),
                            GuestId = new Guid("07e89e34-3b8f-4b25-aa19-102d083d7187"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9510),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("088b1f41-b184-4ea5-aad5-c0031b4059bb"),
                            GuestId = new Guid("5c9ed631-1c4e-4d4b-9287-dbebffcc13c2"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9512),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("088b1f41-b184-4ea5-aad5-c0031b4059bb"),
                            GuestId = new Guid("6f52134a-3010-4e4e-abc2-a1957594a76c"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9514),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("016672c1-6f7a-4673-b739-5805ce970d89"),
                            GuestId = new Guid("434f66a3-5133-4b74-9900-5de8f5f5dc79"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9515),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("13c1556d-411e-4a5f-8bea-fa15646dbbf1"),
                            GuestId = new Guid("07e89e34-3b8f-4b25-aa19-102d083d7187"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9515),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("13c1556d-411e-4a5f-8bea-fa15646dbbf1"),
                            GuestId = new Guid("6f52134a-3010-4e4e-abc2-a1957594a76c"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9516),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("41bdb9ac-86cf-4d52-beb3-690f98ec123b"),
                            GuestId = new Guid("5c9ed631-1c4e-4d4b-9287-dbebffcc13c2"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9517),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("41bdb9ac-86cf-4d52-beb3-690f98ec123b"),
                            GuestId = new Guid("434f66a3-5133-4b74-9900-5de8f5f5dc79"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9518),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CheckinDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckoutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b88f4b65-c8da-46d5-b02e-156e2170a834"),
                            CheckinDate = new DateOnly(2024, 8, 1),
                            CheckoutDate = new DateOnly(2024, 8, 7),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9415),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("78904955-2d0c-4f13-a060-22aa49215c42"),
                            TotalPrice = 9000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("088b1f41-b184-4ea5-aad5-c0031b4059bb"),
                            CheckinDate = new DateOnly(2024, 8, 10),
                            CheckoutDate = new DateOnly(2024, 8, 15),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9427),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("af5b9506-e7cb-4a5c-87a5-6a932078c926"),
                            TotalPrice = 17500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4fb82c6d-fca5-4de7-9245-a3c348e2a219"),
                            CheckinDate = new DateOnly(2024, 9, 1),
                            CheckoutDate = new DateOnly(2024, 9, 4),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9430),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("97948af0-e4da-43cd-9927-8f7556e7048c"),
                            TotalPrice = 2400m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("13c1556d-411e-4a5f-8bea-fa15646dbbf1"),
                            CheckinDate = new DateOnly(2024, 9, 15),
                            CheckoutDate = new DateOnly(2024, 9, 20),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9432),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("580fc069-24ed-4d0f-b647-c4fd32e7a7ae"),
                            TotalPrice = 12500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b0a4ccdb-c3ea-4267-b038-794f758d0efb"),
                            CheckinDate = new DateOnly(2024, 10, 1),
                            CheckoutDate = new DateOnly(2024, 10, 8),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9434),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("fc520449-49a6-476a-bd47-fd59e32cdd4e"),
                            TotalPrice = 14000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("016672c1-6f7a-4673-b739-5805ce970d89"),
                            CheckinDate = new DateOnly(2024, 10, 5),
                            CheckoutDate = new DateOnly(2024, 10, 10),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9436),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("7f1f2582-013d-4437-b208-ea7414ad1cdb"),
                            TotalPrice = 25000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("41bdb9ac-86cf-4d52-beb3-690f98ec123b"),
                            CheckinDate = new DateOnly(2024, 10, 15),
                            CheckoutDate = new DateOnly(2024, 10, 20),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9438),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("0a89147e-a714-47a6-b4ef-99e8820b9012"),
                            TotalPrice = 10000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber")
                        .IsUnique()
                        .HasFilter("[IdentityNumber] IS NOT NULL");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cb35a91-9175-4731-98c4-ace3a91f5643"),
                            Address = "Ankara Çankaya",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9380),
                            DateOfBirth = new DateOnly(1985, 5, 12),
                            Email = "ali.kara@example.com",
                            FirstName = "Ali",
                            IdentityNumber = "98765432101",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kara",
                            Phone = "03121234567",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b7123bd7-dcfd-480b-af66-8a0449e5091e"),
                            Address = "İstanbul Kadıköy",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9386),
                            DateOfBirth = new DateOnly(1990, 9, 23),
                            Email = "veli.yilmaz@example.com",
                            FirstName = "Veli",
                            IdentityNumber = "87654321012",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yılmaz",
                            Phone = "02129876543",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1e587ae7-13be-49c9-aa52-6a21f8778102"),
                            Address = "İzmir Bornova",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9388),
                            DateOfBirth = new DateOnly(1982, 4, 5),
                            Email = "ayse.yurt@example.com",
                            FirstName = "Ayşe",
                            IdentityNumber = "76543210923",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yurt",
                            Phone = "02325252525",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ac616ce8-f79f-499b-8538-90ae2245c480"),
                            Address = "Antalya Lara",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9390),
                            DateOfBirth = new DateOnly(1975, 11, 15),
                            Email = "mehmet.celik@example.com",
                            FirstName = "Mehmet",
                            IdentityNumber = "65432109834",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Çelik",
                            Phone = "02426262626",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("86806108-b61b-4ace-90a4-3022a65b4ed0"),
                            Address = "Bolu Merkez",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9392),
                            DateOfBirth = new DateOnly(1993, 6, 19),
                            Email = "zeynep.arslan@example.com",
                            FirstName = "Zeynep",
                            IdentityNumber = "54321098745",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Arslan",
                            Phone = "03782567891",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("295e1506-5428-4fb9-8805-061aced2e2b0"),
                            Address = "Trabzon Akçaabat",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9393),
                            DateOfBirth = new DateOnly(1988, 2, 8),
                            Email = "huseyin.koc@example.com",
                            FirstName = "Hüseyin",
                            IdentityNumber = "43210987656",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Koç",
                            Phone = "04622987654",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ad2493d2-3fdc-44b0-a867-21d8592045b7"),
                            Address = "Kayseri Melikgazi",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9395),
                            DateOfBirth = new DateOnly(1997, 8, 30),
                            Email = "elif.guven@example.com",
                            FirstName = "Elif",
                            IdentityNumber = "32109876567",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Güven",
                            Phone = "03512345678",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("07e89e34-3b8f-4b25-aa19-102d083d7187"),
                            Address = "Ankara Etimesgut",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9491),
                            DateOfBirth = new DateOnly(1994, 11, 12),
                            Email = "derya.kaya@example.com",
                            FirstName = "Derya",
                            IdentityNumber = "56789012345",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kaya",
                            Phone = "03134567890",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5c9ed631-1c4e-4d4b-9287-dbebffcc13c2"),
                            Address = "İzmir Karşıyaka",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9493),
                            DateOfBirth = new DateOnly(1987, 6, 25),
                            Email = "gokhan.aydin@example.com",
                            FirstName = "Gökhan",
                            IdentityNumber = "67890123456",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Aydın",
                            Phone = "02345678901",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f52134a-3010-4e4e-abc2-a1957594a76c"),
                            Address = "Bursa Osmangazi",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9494),
                            DateOfBirth = new DateOnly(1995, 3, 8),
                            Email = "eylul.yalcin@example.com",
                            FirstName = "Eylül",
                            IdentityNumber = "78901234567",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yalçın",
                            Phone = "02225678901",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("17fce284-3b95-4c98-a2dd-0f6e35dbe842"),
                            Address = "Konya Meram",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9496),
                            DateOfBirth = new DateOnly(1989, 7, 20),
                            Email = "mert.yilmaz@example.com",
                            FirstName = "Mert",
                            IdentityNumber = "89012345678",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yılmaz",
                            Phone = "03325678901",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("434f66a3-5133-4b74-9900-5de8f5f5dc79"),
                            Address = "İstanbul Beylikdüzü",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9497),
                            DateOfBirth = new DateOnly(1992, 10, 30),
                            Email = "seda.demirtas@example.com",
                            FirstName = "Seda",
                            IdentityNumber = "90123456789",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Demirtaş",
                            Phone = "02124567890",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly>("CheckinTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckoutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("Stars")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72b94698-b471-4d94-9b22-b15013986051"),
                            Address = "İstanbul/Beşiktaş",
                            CheckinTime = new TimeOnly(14, 0, 0),
                            CheckoutTime = new TimeOnly(12, 0, 0),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9228),
                            Email = "grandhorizon@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Grand Horizon",
                            Phone = "02121234567",
                            Stars = (byte)4,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5723b7af-8968-4554-b471-0f36b63fb6a6"),
                            Address = "Antalya/Kaleiçi",
                            CheckinTime = new TimeOnly(15, 0, 0),
                            CheckoutTime = new TimeOnly(11, 0, 0),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9241),
                            Email = "seasideresort@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Seaside Resort",
                            Phone = "02428888888",
                            Stars = (byte)5,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("39dd0a88-b29f-4a9a-905a-d8ad20f64e4f"),
                            Address = "Bolu/Yedigöller",
                            CheckinTime = new TimeOnly(13, 0, 0),
                            CheckoutTime = new TimeOnly(10, 0, 0),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9244),
                            Email = "mountainlodge@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mountain Lodge",
                            Phone = "03782567890",
                            Stars = (byte)3,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78904955-2d0c-4f13-a060-22aa49215c42"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9345),
                            HotelId = new Guid("72b94698-b471-4d94-9b22-b15013986051"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 101,
                            RoomTypeId = new Guid("9ebbc780-28c1-473f-a78d-523831110fe6"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("af5b9506-e7cb-4a5c-87a5-6a932078c926"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9347),
                            HotelId = new Guid("72b94698-b471-4d94-9b22-b15013986051"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 102,
                            RoomTypeId = new Guid("4b6cc5bd-8ae2-4bff-ab6f-36e2daa4f238"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("97948af0-e4da-43cd-9927-8f7556e7048c"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9349),
                            HotelId = new Guid("5723b7af-8968-4554-b471-0f36b63fb6a6"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 201,
                            RoomTypeId = new Guid("ff4a57be-b09e-49fd-8a63-32cb98f48368"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("580fc069-24ed-4d0f-b647-c4fd32e7a7ae"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9350),
                            HotelId = new Guid("5723b7af-8968-4554-b471-0f36b63fb6a6"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 202,
                            RoomTypeId = new Guid("875da4e9-144c-433a-b047-4acee9c0ab3f"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fc520449-49a6-476a-bd47-fd59e32cdd4e"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9351),
                            HotelId = new Guid("39dd0a88-b29f-4a9a-905a-d8ad20f64e4f"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 301,
                            RoomTypeId = new Guid("55d56d46-185c-48a3-afac-5861189df945"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fbe62d94-1d3f-4e18-a690-d996afa6aa75"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9352),
                            HotelId = new Guid("39dd0a88-b29f-4a9a-905a-d8ad20f64e4f"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 302,
                            RoomTypeId = new Guid("9ebbc780-28c1-473f-a78d-523831110fe6"),
                            Status = "Occupied",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7f1f2582-013d-4437-b208-ea7414ad1cdb"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9353),
                            HotelId = new Guid("39dd0a88-b29f-4a9a-905a-d8ad20f64e4f"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 303,
                            RoomTypeId = new Guid("4b6cc5bd-8ae2-4bff-ab6f-36e2daa4f238"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0a89147e-a714-47a6-b4ef-99e8820b9012"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9355),
                            HotelId = new Guid("5723b7af-8968-4554-b471-0f36b63fb6a6"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 401,
                            RoomTypeId = new Guid("55d56d46-185c-48a3-afac-5861189df945"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b2296c96-151c-455d-ac23-7371de6e3c68"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9357),
                            HotelId = new Guid("5723b7af-8968-4554-b471-0f36b63fb6a6"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 402,
                            RoomTypeId = new Guid("ff4a57be-b09e-49fd-8a63-32cb98f48368"),
                            Status = "Occupied",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Capacity")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ebbc780-28c1-473f-a78d-523831110fe6"),
                            Capacity = (byte)2,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9314),
                            Description = "Spacious room with modern amenities",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Superior",
                            PricePerNight = 1500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4b6cc5bd-8ae2-4bff-ab6f-36e2daa4f238"),
                            Capacity = (byte)4,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9318),
                            Description = "Luxurious top-floor room with city view",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Royal S",
                            PricePerNight = 3500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ff4a57be-b09e-49fd-8a63-32cb98f48368"),
                            Capacity = (byte)1,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9319),
                            Description = "Standard room with basic facilities",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Classic",
                            PricePerNight = 800m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("875da4e9-144c-433a-b047-4acee9c0ab3f"),
                            Capacity = (byte)3,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9321),
                            Description = "Suite with separate living and sleeping areas",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Executive",
                            PricePerNight = 2500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("55d56d46-185c-48a3-afac-5861189df945"),
                            Capacity = (byte)3,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 26, 42, 624, DateTimeKind.Local).AddTicks(9322),
                            Description = "Comfortable suite with additional space",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Standard",
                            PricePerNight = 2000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.BRBookingGuest", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", "Booking")
                        .WithMany("BRBookingGuests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", "Guest")
                        .WithMany("BRBookingGuests")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Payment", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Staff", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", "Hotel")
                        .WithMany("Staffs")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.Navigation("BRBookingGuests");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", b =>
                {
                    b.Navigation("BRBookingGuests");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
