// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YB_MelihEfeOmer_RezervasyonApp.DataAccess.Context;

#nullable disable

namespace YB_MelihEfeOmer_RezervasyonApp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240726082048_newDataSetted5")]
    partial class newDataSetted5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.BRBookingGuest", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId", "GuestId");

                    b.HasIndex("GuestId");

                    b.ToTable("BRBookingGuests");

                    b.HasData(
                        new
                        {
                            BookingId = new Guid("c2812a82-964d-4316-921d-082021dbff2b"),
                            GuestId = new Guid("e4c6401f-c088-40c1-933f-a3fe5a44877d"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8928),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("b3164b86-7d06-4d61-8b96-bd5d64678b0f"),
                            GuestId = new Guid("6253468b-cb86-4b62-8af3-58fe1bd3b41b"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8930),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("6171fb42-0bbe-42ca-a1aa-c68c5cb1702c"),
                            GuestId = new Guid("683fc9b9-3720-48ed-b099-dde2adc3642f"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8931),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("c162c01f-1f9f-4217-b8a1-471c89eabacb"),
                            GuestId = new Guid("a876fc73-5bc1-41e7-8260-b16000f5108f"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8932),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("ee1ae452-8622-407c-bd31-6ebf53017602"),
                            GuestId = new Guid("a4bc697e-4d84-427b-9fc4-6658dc109311"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8933),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("0990a4f9-c889-4869-91d4-d1a877f7bdec"),
                            GuestId = new Guid("599afa1b-7344-411f-af5d-64629d57881e"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8935),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("04128377-6194-487d-9f23-83c41f1e3b09"),
                            GuestId = new Guid("98e0c313-607b-4821-a372-c89749e0767c"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8935),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("b3164b86-7d06-4d61-8b96-bd5d64678b0f"),
                            GuestId = new Guid("8e927139-f5c7-4452-9773-68373c1782fa"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8992),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("b3164b86-7d06-4d61-8b96-bd5d64678b0f"),
                            GuestId = new Guid("dafdf0dd-2e70-41b7-9f04-7df40fb1ca63"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8993),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("b3164b86-7d06-4d61-8b96-bd5d64678b0f"),
                            GuestId = new Guid("4c6dc875-c3d4-4465-b330-e6d12f397a0a"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8994),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("b3164b86-7d06-4d61-8b96-bd5d64678b0f"),
                            GuestId = new Guid("2645fc2a-aef1-4ba5-b255-14d173d9a2fc"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8995),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("0990a4f9-c889-4869-91d4-d1a877f7bdec"),
                            GuestId = new Guid("3ed2c82d-5090-4358-8692-17d3f525adcb"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8997),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("c162c01f-1f9f-4217-b8a1-471c89eabacb"),
                            GuestId = new Guid("8e927139-f5c7-4452-9773-68373c1782fa"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8998),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("c162c01f-1f9f-4217-b8a1-471c89eabacb"),
                            GuestId = new Guid("4c6dc875-c3d4-4465-b330-e6d12f397a0a"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8999),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("04128377-6194-487d-9f23-83c41f1e3b09"),
                            GuestId = new Guid("dafdf0dd-2e70-41b7-9f04-7df40fb1ca63"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(9000),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("04128377-6194-487d-9f23-83c41f1e3b09"),
                            GuestId = new Guid("3ed2c82d-5090-4358-8692-17d3f525adcb"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(9001),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CheckinDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckoutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2812a82-964d-4316-921d-082021dbff2b"),
                            CheckinDate = new DateOnly(2024, 8, 1),
                            CheckoutDate = new DateOnly(2024, 8, 7),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8887),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("bc13bed4-0aa8-4047-9076-4d00e76e8dc7"),
                            TotalPrice = 9000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b3164b86-7d06-4d61-8b96-bd5d64678b0f"),
                            CheckinDate = new DateOnly(2024, 8, 10),
                            CheckoutDate = new DateOnly(2024, 8, 15),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8901),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("7f430e33-cdb0-4cf7-998f-ca7c23fc0f08"),
                            TotalPrice = 17500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6171fb42-0bbe-42ca-a1aa-c68c5cb1702c"),
                            CheckinDate = new DateOnly(2024, 9, 1),
                            CheckoutDate = new DateOnly(2024, 9, 4),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8903),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("5acb0baa-063d-4c45-8545-d9d50b548d56"),
                            TotalPrice = 2400m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c162c01f-1f9f-4217-b8a1-471c89eabacb"),
                            CheckinDate = new DateOnly(2024, 9, 15),
                            CheckoutDate = new DateOnly(2024, 9, 20),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8905),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("7c2cbe0b-4e5d-4c38-8d85-69edc6c8cfb9"),
                            TotalPrice = 12500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ee1ae452-8622-407c-bd31-6ebf53017602"),
                            CheckinDate = new DateOnly(2024, 10, 1),
                            CheckoutDate = new DateOnly(2024, 10, 8),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8908),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("07311b31-cd85-4ea9-ba98-cea1a3e20aad"),
                            TotalPrice = 14000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0990a4f9-c889-4869-91d4-d1a877f7bdec"),
                            CheckinDate = new DateOnly(2024, 10, 5),
                            CheckoutDate = new DateOnly(2024, 10, 10),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8910),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("7398466f-dc74-4809-a44a-fdafbffc9e75"),
                            TotalPrice = 25000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("04128377-6194-487d-9f23-83c41f1e3b09"),
                            CheckinDate = new DateOnly(2024, 10, 15),
                            CheckoutDate = new DateOnly(2024, 10, 20),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8912),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("866465a1-e1fc-455e-8bff-fbb0fae04182"),
                            TotalPrice = 10000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber")
                        .IsUnique()
                        .HasFilter("[IdentityNumber] IS NOT NULL");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4c6401f-c088-40c1-933f-a3fe5a44877d"),
                            Address = "Ankara Çankaya",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8849),
                            DateOfBirth = new DateOnly(1985, 5, 12),
                            Email = "ali.kara@example.com",
                            FirstName = "Ali",
                            IdentityNumber = "98765432101",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kara",
                            Phone = "03121234567",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6253468b-cb86-4b62-8af3-58fe1bd3b41b"),
                            Address = "İstanbul Kadıköy",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8857),
                            DateOfBirth = new DateOnly(1990, 9, 23),
                            Email = "veli.yilmaz@example.com",
                            FirstName = "Veli",
                            IdentityNumber = "87654321012",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yılmaz",
                            Phone = "02129876543",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("683fc9b9-3720-48ed-b099-dde2adc3642f"),
                            Address = "İzmir Bornova",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8861),
                            DateOfBirth = new DateOnly(1982, 4, 5),
                            Email = "ayse.yurt@example.com",
                            FirstName = "Ayşe",
                            IdentityNumber = "76543210923",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yurt",
                            Phone = "02325252525",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a876fc73-5bc1-41e7-8260-b16000f5108f"),
                            Address = "Antalya Lara",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8862),
                            DateOfBirth = new DateOnly(1975, 11, 15),
                            Email = "mehmet.celik@example.com",
                            FirstName = "Mehmet",
                            IdentityNumber = "65432109834",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Çelik",
                            Phone = "02426262626",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a4bc697e-4d84-427b-9fc4-6658dc109311"),
                            Address = "Bolu Merkez",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8864),
                            DateOfBirth = new DateOnly(1993, 6, 19),
                            Email = "zeynep.arslan@example.com",
                            FirstName = "Zeynep",
                            IdentityNumber = "54321098745",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Arslan",
                            Phone = "03782567891",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("599afa1b-7344-411f-af5d-64629d57881e"),
                            Address = "Trabzon Akçaabat",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8866),
                            DateOfBirth = new DateOnly(1988, 2, 8),
                            Email = "huseyin.koc@example.com",
                            FirstName = "Hüseyin",
                            IdentityNumber = "43210987656",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Koç",
                            Phone = "04622987654",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("98e0c313-607b-4821-a372-c89749e0767c"),
                            Address = "Kayseri Melikgazi",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8868),
                            DateOfBirth = new DateOnly(1997, 8, 30),
                            Email = "elif.guven@example.com",
                            FirstName = "Elif",
                            IdentityNumber = "32109876567",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Güven",
                            Phone = "03512345678",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8e927139-f5c7-4452-9773-68373c1782fa"),
                            Address = "Ankara Etimesgut",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8950),
                            DateOfBirth = new DateOnly(1994, 11, 12),
                            Email = "derya.kaya@example.com",
                            FirstName = "Derya",
                            IdentityNumber = "56789012345",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kaya",
                            Phone = "03134567890",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dafdf0dd-2e70-41b7-9f04-7df40fb1ca63"),
                            Address = "İzmir Karşıyaka",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8954),
                            DateOfBirth = new DateOnly(1987, 6, 25),
                            Email = "gokhan.aydin@example.com",
                            FirstName = "Gökhan",
                            IdentityNumber = "67890123456",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Aydın",
                            Phone = "02345678901",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4c6dc875-c3d4-4465-b330-e6d12f397a0a"),
                            Address = "Bursa Osmangazi",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8955),
                            DateOfBirth = new DateOnly(1995, 3, 8),
                            Email = "eylul.yalcin@example.com",
                            FirstName = "Eylül",
                            IdentityNumber = "78901234567",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yalçın",
                            Phone = "02225678901",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2645fc2a-aef1-4ba5-b255-14d173d9a2fc"),
                            Address = "Konya Meram",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8957),
                            DateOfBirth = new DateOnly(1989, 7, 20),
                            Email = "mert.yilmaz@example.com",
                            FirstName = "Mert",
                            IdentityNumber = "89012345678",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yılmaz",
                            Phone = "03325678901",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3ed2c82d-5090-4358-8692-17d3f525adcb"),
                            Address = "İstanbul Beylikdüzü",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8959),
                            DateOfBirth = new DateOnly(1992, 10, 30),
                            Email = "seda.demirtas@example.com",
                            FirstName = "Seda",
                            IdentityNumber = "90123456789",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Demirtaş",
                            Phone = "02124567890",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly>("CheckinTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckoutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("Stars")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26055b9f-4dea-4286-aeb9-a92ddb45b1bf"),
                            Address = "İstanbul/Beşiktaş",
                            CheckinTime = new TimeOnly(14, 0, 0),
                            CheckoutTime = new TimeOnly(12, 0, 0),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8689),
                            Email = "grandhorizon@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Grand Horizon",
                            Phone = "02121234567",
                            Stars = (byte)4,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("49312820-250b-4f73-b7e8-a74a45ff7aeb"),
                            Address = "Antalya/Kaleiçi",
                            CheckinTime = new TimeOnly(15, 0, 0),
                            CheckoutTime = new TimeOnly(11, 0, 0),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8704),
                            Email = "seasideresort@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Seaside Resort",
                            Phone = "02428888888",
                            Stars = (byte)5,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("78554b09-9daa-435b-adbb-45f0f092aec9"),
                            Address = "Bolu/Yedigöller",
                            CheckinTime = new TimeOnly(13, 0, 0),
                            CheckoutTime = new TimeOnly(10, 0, 0),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8706),
                            Email = "mountainlodge@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mountain Lodge",
                            Phone = "03782567890",
                            Stars = (byte)3,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc13bed4-0aa8-4047-9076-4d00e76e8dc7"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8814),
                            HotelId = new Guid("26055b9f-4dea-4286-aeb9-a92ddb45b1bf"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 101,
                            RoomTypeId = new Guid("e71394f8-56fa-42dd-8efb-441227947720"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7f430e33-cdb0-4cf7-998f-ca7c23fc0f08"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8817),
                            HotelId = new Guid("26055b9f-4dea-4286-aeb9-a92ddb45b1bf"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 102,
                            RoomTypeId = new Guid("8ce9c3e7-eb53-4039-9c68-936c0cb103d1"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5acb0baa-063d-4c45-8545-d9d50b548d56"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8820),
                            HotelId = new Guid("49312820-250b-4f73-b7e8-a74a45ff7aeb"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 201,
                            RoomTypeId = new Guid("819e11f8-0f98-48ac-94cd-779705cfede3"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7c2cbe0b-4e5d-4c38-8d85-69edc6c8cfb9"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8821),
                            HotelId = new Guid("49312820-250b-4f73-b7e8-a74a45ff7aeb"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 202,
                            RoomTypeId = new Guid("96d889c4-68e5-400d-a7a3-8780f95aef07"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("07311b31-cd85-4ea9-ba98-cea1a3e20aad"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8823),
                            HotelId = new Guid("78554b09-9daa-435b-adbb-45f0f092aec9"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 301,
                            RoomTypeId = new Guid("83bc4a50-3a6c-4b78-b153-7d6574f6d793"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fbdf305b-a041-42fb-874f-69d743a0129f"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8824),
                            HotelId = new Guid("78554b09-9daa-435b-adbb-45f0f092aec9"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 302,
                            RoomTypeId = new Guid("e71394f8-56fa-42dd-8efb-441227947720"),
                            Status = "Occupied",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7398466f-dc74-4809-a44a-fdafbffc9e75"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8825),
                            HotelId = new Guid("78554b09-9daa-435b-adbb-45f0f092aec9"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 303,
                            RoomTypeId = new Guid("8ce9c3e7-eb53-4039-9c68-936c0cb103d1"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("866465a1-e1fc-455e-8bff-fbb0fae04182"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8826),
                            HotelId = new Guid("49312820-250b-4f73-b7e8-a74a45ff7aeb"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 401,
                            RoomTypeId = new Guid("83bc4a50-3a6c-4b78-b153-7d6574f6d793"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8d98bfb0-56dd-42cc-bc81-5dbbc5cee506"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8828),
                            HotelId = new Guid("49312820-250b-4f73-b7e8-a74a45ff7aeb"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 402,
                            RoomTypeId = new Guid("819e11f8-0f98-48ac-94cd-779705cfede3"),
                            Status = "Occupied",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Capacity")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e71394f8-56fa-42dd-8efb-441227947720"),
                            Capacity = (byte)2,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8783),
                            Description = "Spacious room with modern amenities",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Superior",
                            PricePerNight = 1500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8ce9c3e7-eb53-4039-9c68-936c0cb103d1"),
                            Capacity = (byte)4,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8790),
                            Description = "Luxurious top-floor room with city view",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Royal S",
                            PricePerNight = 3500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("819e11f8-0f98-48ac-94cd-779705cfede3"),
                            Capacity = (byte)1,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8791),
                            Description = "Standard room with basic facilities",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Classic",
                            PricePerNight = 800m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("96d889c4-68e5-400d-a7a3-8780f95aef07"),
                            Capacity = (byte)3,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8793),
                            Description = "Suite with separate living and sleeping areas",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Executive",
                            PricePerNight = 2500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("83bc4a50-3a6c-4b78-b153-7d6574f6d793"),
                            Capacity = (byte)3,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 20, 48, 661, DateTimeKind.Local).AddTicks(8794),
                            Description = "Comfortable suite with additional space",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Standard",
                            PricePerNight = 2000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.BRBookingGuest", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", "Booking")
                        .WithMany("BRBookingGuests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", "Guest")
                        .WithMany("BRBookingGuests")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Payment", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Staff", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", "Hotel")
                        .WithMany("Staffs")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.Navigation("BRBookingGuests");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", b =>
                {
                    b.Navigation("BRBookingGuests");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
