// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YB_MelihEfeOmer_RezervasyonApp.DataAccess.Context;

#nullable disable

namespace YB_MelihEfeOmer_RezervasyonApp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240726081847_newDataSetted4")]
    partial class newDataSetted4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.BRBookingGuest", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId", "GuestId");

                    b.HasIndex("GuestId");

                    b.ToTable("BRBookingGuests");

                    b.HasData(
                        new
                        {
                            BookingId = new Guid("6f05fac4-6ec6-4c0a-9130-13ba033e2407"),
                            GuestId = new Guid("2c845461-aca4-44b2-a8a6-a2ad0cc04777"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5560),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("1cd83c31-de1f-419a-99ea-54d680363302"),
                            GuestId = new Guid("dde1efdd-811e-48f8-89b4-815a7ec284bd"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5562),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("cf8811eb-4d64-4626-ad6e-2626561ce044"),
                            GuestId = new Guid("eb46ab5c-6ba1-44bf-90b1-d4177d070771"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5563),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("688857a4-d44e-43a3-84f7-3b80028ce3a8"),
                            GuestId = new Guid("63238c02-8f49-42fd-9a6c-63b07a0a2c3e"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5564),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("771ffbe2-ff52-42e7-ac6c-a622a2151240"),
                            GuestId = new Guid("4b81d1c1-1636-4b78-8b06-1b2726ef2814"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5566),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("8dbcfbf1-3bc5-4ed1-8942-c2278dd6ae6a"),
                            GuestId = new Guid("914e95c7-59d7-4e60-94a7-822b16bf409b"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5567),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("58cd8298-3cdf-41be-8492-ca8d764ca9b9"),
                            GuestId = new Guid("af3d13c1-9aeb-4fe6-9fa6-59d0ea34a281"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5568),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("1cd83c31-de1f-419a-99ea-54d680363302"),
                            GuestId = new Guid("609fa045-92ab-4fc2-bd4d-9d010590cf1e"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5604),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("1cd83c31-de1f-419a-99ea-54d680363302"),
                            GuestId = new Guid("266c13e1-0715-42e0-b2ff-87408a3cfd40"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5605),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("1cd83c31-de1f-419a-99ea-54d680363302"),
                            GuestId = new Guid("d72c3831-717a-44a9-9c81-daab97528618"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5606),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("1cd83c31-de1f-419a-99ea-54d680363302"),
                            GuestId = new Guid("12735335-a78b-4d9f-9b2f-5d374622b73a"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5608),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("8dbcfbf1-3bc5-4ed1-8942-c2278dd6ae6a"),
                            GuestId = new Guid("50559e11-8527-4db3-83e5-6eb2733fd481"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5609),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("688857a4-d44e-43a3-84f7-3b80028ce3a8"),
                            GuestId = new Guid("609fa045-92ab-4fc2-bd4d-9d010590cf1e"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5610),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("688857a4-d44e-43a3-84f7-3b80028ce3a8"),
                            GuestId = new Guid("d72c3831-717a-44a9-9c81-daab97528618"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5610),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("58cd8298-3cdf-41be-8492-ca8d764ca9b9"),
                            GuestId = new Guid("266c13e1-0715-42e0-b2ff-87408a3cfd40"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5611),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("58cd8298-3cdf-41be-8492-ca8d764ca9b9"),
                            GuestId = new Guid("50559e11-8527-4db3-83e5-6eb2733fd481"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5612),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CheckinDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckoutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f05fac4-6ec6-4c0a-9130-13ba033e2407"),
                            CheckinDate = new DateOnly(2024, 8, 1),
                            CheckoutDate = new DateOnly(2024, 8, 7),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5499),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("09982455-dadd-48e3-a450-86dcae1a9635"),
                            TotalPrice = 9000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1cd83c31-de1f-419a-99ea-54d680363302"),
                            CheckinDate = new DateOnly(2024, 8, 10),
                            CheckoutDate = new DateOnly(2024, 8, 15),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5514),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("6921376a-a9b1-4665-995a-ac8dc43d404d"),
                            TotalPrice = 17500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cf8811eb-4d64-4626-ad6e-2626561ce044"),
                            CheckinDate = new DateOnly(2024, 9, 1),
                            CheckoutDate = new DateOnly(2024, 9, 4),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5516),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("b79b6afe-d191-481b-bba9-71a180e7be43"),
                            TotalPrice = 2400m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("688857a4-d44e-43a3-84f7-3b80028ce3a8"),
                            CheckinDate = new DateOnly(2024, 9, 15),
                            CheckoutDate = new DateOnly(2024, 9, 20),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5519),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("71b7ea8e-43c4-41f3-be97-b1330ae324a3"),
                            TotalPrice = 12500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("771ffbe2-ff52-42e7-ac6c-a622a2151240"),
                            CheckinDate = new DateOnly(2024, 10, 1),
                            CheckoutDate = new DateOnly(2024, 10, 8),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5521),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("72eb3075-4e1a-4568-a9ef-2baa57815b5d"),
                            TotalPrice = 14000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8dbcfbf1-3bc5-4ed1-8942-c2278dd6ae6a"),
                            CheckinDate = new DateOnly(2024, 10, 5),
                            CheckoutDate = new DateOnly(2024, 10, 10),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5523),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("012c9631-8c0a-4bba-bab3-b543f86a557b"),
                            TotalPrice = 25000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("58cd8298-3cdf-41be-8492-ca8d764ca9b9"),
                            CheckinDate = new DateOnly(2024, 10, 15),
                            CheckoutDate = new DateOnly(2024, 10, 20),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5525),
                            IsActive = true,
                            IsDeleted = false,
                            RoomId = new Guid("dcb1e0b9-5caa-47b8-96be-8faffe2bd419"),
                            TotalPrice = 10000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber")
                        .IsUnique()
                        .HasFilter("[IdentityNumber] IS NOT NULL");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c845461-aca4-44b2-a8a6-a2ad0cc04777"),
                            Address = "Ankara Çankaya",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5462),
                            DateOfBirth = new DateOnly(1985, 5, 12),
                            Email = "ali.kara@example.com",
                            FirstName = "Ali",
                            IdentityNumber = "98765432101",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kara",
                            Phone = "03121234567",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dde1efdd-811e-48f8-89b4-815a7ec284bd"),
                            Address = "İstanbul Kadıköy",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5471),
                            DateOfBirth = new DateOnly(1990, 9, 23),
                            Email = "veli.yilmaz@example.com",
                            FirstName = "Veli",
                            IdentityNumber = "87654321012",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yılmaz",
                            Phone = "02129876543",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("eb46ab5c-6ba1-44bf-90b1-d4177d070771"),
                            Address = "İzmir Bornova",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5473),
                            DateOfBirth = new DateOnly(1982, 4, 5),
                            Email = "ayse.yurt@example.com",
                            FirstName = "Ayşe",
                            IdentityNumber = "76543210923",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yurt",
                            Phone = "02325252525",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("63238c02-8f49-42fd-9a6c-63b07a0a2c3e"),
                            Address = "Antalya Lara",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5474),
                            DateOfBirth = new DateOnly(1975, 11, 15),
                            Email = "mehmet.celik@example.com",
                            FirstName = "Mehmet",
                            IdentityNumber = "65432109834",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Çelik",
                            Phone = "02426262626",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4b81d1c1-1636-4b78-8b06-1b2726ef2814"),
                            Address = "Bolu Merkez",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5476),
                            DateOfBirth = new DateOnly(1993, 6, 19),
                            Email = "zeynep.arslan@example.com",
                            FirstName = "Zeynep",
                            IdentityNumber = "54321098745",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Arslan",
                            Phone = "03782567891",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("914e95c7-59d7-4e60-94a7-822b16bf409b"),
                            Address = "Trabzon Akçaabat",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5477),
                            DateOfBirth = new DateOnly(1988, 2, 8),
                            Email = "huseyin.koc@example.com",
                            FirstName = "Hüseyin",
                            IdentityNumber = "43210987656",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Koç",
                            Phone = "04622987654",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("af3d13c1-9aeb-4fe6-9fa6-59d0ea34a281"),
                            Address = "Kayseri Melikgazi",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5479),
                            DateOfBirth = new DateOnly(1997, 8, 30),
                            Email = "elif.guven@example.com",
                            FirstName = "Elif",
                            IdentityNumber = "32109876567",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Güven",
                            Phone = "03512345678",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("609fa045-92ab-4fc2-bd4d-9d010590cf1e"),
                            Address = "Ankara Etimesgut",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5585),
                            DateOfBirth = new DateOnly(1994, 11, 12),
                            Email = "derya.kaya@example.com",
                            FirstName = "Derya",
                            IdentityNumber = "56789012345",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Kaya",
                            Phone = "03134567890",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("266c13e1-0715-42e0-b2ff-87408a3cfd40"),
                            Address = "İzmir Karşıyaka",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5587),
                            DateOfBirth = new DateOnly(1987, 6, 25),
                            Email = "gokhan.aydin@example.com",
                            FirstName = "Gökhan",
                            IdentityNumber = "67890123456",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Aydın",
                            Phone = "02345678901",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d72c3831-717a-44a9-9c81-daab97528618"),
                            Address = "Bursa Osmangazi",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5588),
                            DateOfBirth = new DateOnly(1995, 3, 8),
                            Email = "eylul.yalcin@example.com",
                            FirstName = "Eylül",
                            IdentityNumber = "78901234567",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yalçın",
                            Phone = "02225678901",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("12735335-a78b-4d9f-9b2f-5d374622b73a"),
                            Address = "Konya Meram",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5590),
                            DateOfBirth = new DateOnly(1989, 7, 20),
                            Email = "mert.yilmaz@example.com",
                            FirstName = "Mert",
                            IdentityNumber = "89012345678",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yılmaz",
                            Phone = "03325678901",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("50559e11-8527-4db3-83e5-6eb2733fd481"),
                            Address = "İstanbul Beylikdüzü",
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5591),
                            DateOfBirth = new DateOnly(1992, 10, 30),
                            Email = "seda.demirtas@example.com",
                            FirstName = "Seda",
                            IdentityNumber = "90123456789",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Demirtaş",
                            Phone = "02124567890",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly>("CheckinTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckoutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("Stars")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac1232b0-5e97-44c1-86d8-9f7fc8d705cd"),
                            Address = "İstanbul/Beşiktaş",
                            CheckinTime = new TimeOnly(14, 0, 0),
                            CheckoutTime = new TimeOnly(12, 0, 0),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5301),
                            Email = "grandhorizon@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Grand Horizon",
                            Phone = "02121234567",
                            Stars = (byte)4,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e99209ed-bf91-4d6a-8216-f1442e793d59"),
                            Address = "Antalya/Kaleiçi",
                            CheckinTime = new TimeOnly(15, 0, 0),
                            CheckoutTime = new TimeOnly(11, 0, 0),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5318),
                            Email = "seasideresort@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Seaside Resort",
                            Phone = "02428888888",
                            Stars = (byte)5,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("20c95b7a-ae09-43cd-bcbc-2539544a31ac"),
                            Address = "Bolu/Yedigöller",
                            CheckinTime = new TimeOnly(13, 0, 0),
                            CheckoutTime = new TimeOnly(10, 0, 0),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5320),
                            Email = "mountainlodge@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mountain Lodge",
                            Phone = "03782567890",
                            Stars = (byte)3,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09982455-dadd-48e3-a450-86dcae1a9635"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5424),
                            HotelId = new Guid("ac1232b0-5e97-44c1-86d8-9f7fc8d705cd"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 101,
                            RoomTypeId = new Guid("b6f443f2-c6ca-46e4-8a54-c7b3b4827ea8"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6921376a-a9b1-4665-995a-ac8dc43d404d"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5430),
                            HotelId = new Guid("ac1232b0-5e97-44c1-86d8-9f7fc8d705cd"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 102,
                            RoomTypeId = new Guid("fd88e90e-2eb7-4f37-89e3-9bf4d17da174"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b79b6afe-d191-481b-bba9-71a180e7be43"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5431),
                            HotelId = new Guid("e99209ed-bf91-4d6a-8216-f1442e793d59"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 201,
                            RoomTypeId = new Guid("63cedc4d-0449-490d-908c-2c8d24efb129"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("71b7ea8e-43c4-41f3-be97-b1330ae324a3"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5432),
                            HotelId = new Guid("e99209ed-bf91-4d6a-8216-f1442e793d59"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 202,
                            RoomTypeId = new Guid("e1484ce7-5f40-4d0f-b59d-1242521d0e52"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("72eb3075-4e1a-4568-a9ef-2baa57815b5d"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5434),
                            HotelId = new Guid("20c95b7a-ae09-43cd-bcbc-2539544a31ac"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 301,
                            RoomTypeId = new Guid("a582c99d-df8b-422f-aaf3-df064cd80092"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f759a038-3425-4f76-bb37-42f1b7047f8b"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5435),
                            HotelId = new Guid("20c95b7a-ae09-43cd-bcbc-2539544a31ac"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 302,
                            RoomTypeId = new Guid("b6f443f2-c6ca-46e4-8a54-c7b3b4827ea8"),
                            Status = "Occupied",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("012c9631-8c0a-4bba-bab3-b543f86a557b"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5436),
                            HotelId = new Guid("20c95b7a-ae09-43cd-bcbc-2539544a31ac"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 303,
                            RoomTypeId = new Guid("fd88e90e-2eb7-4f37-89e3-9bf4d17da174"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dcb1e0b9-5caa-47b8-96be-8faffe2bd419"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5437),
                            HotelId = new Guid("e99209ed-bf91-4d6a-8216-f1442e793d59"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 401,
                            RoomTypeId = new Guid("a582c99d-df8b-422f-aaf3-df064cd80092"),
                            Status = "Available",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("90e7bf50-ec8f-4ba6-b0d7-a411801fa659"),
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5438),
                            HotelId = new Guid("e99209ed-bf91-4d6a-8216-f1442e793d59"),
                            IsActive = true,
                            IsDeleted = false,
                            RoomNumber = 402,
                            RoomTypeId = new Guid("63cedc4d-0449-490d-908c-2c8d24efb129"),
                            Status = "Occupied",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Capacity")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6f443f2-c6ca-46e4-8a54-c7b3b4827ea8"),
                            Capacity = (byte)2,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5392),
                            Description = "Spacious room with modern amenities",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Superior",
                            PricePerNight = 1500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fd88e90e-2eb7-4f37-89e3-9bf4d17da174"),
                            Capacity = (byte)4,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5397),
                            Description = "Luxurious top-floor room with city view",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Penthouse",
                            PricePerNight = 3500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("63cedc4d-0449-490d-908c-2c8d24efb129"),
                            Capacity = (byte)1,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5399),
                            Description = "Standard room with basic facilities",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Classic",
                            PricePerNight = 800m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1484ce7-5f40-4d0f-b59d-1242521d0e52"),
                            Capacity = (byte)3,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5400),
                            Description = "Suite with separate living and sleeping areas",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Executive Suite",
                            PricePerNight = 2500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a582c99d-df8b-422f-aaf3-df064cd80092"),
                            Capacity = (byte)3,
                            CreatedTime = new DateTime(2024, 7, 26, 11, 18, 47, 278, DateTimeKind.Local).AddTicks(5402),
                            Description = "Comfortable suite with additional space",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Standard Suite",
                            PricePerNight = 2000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.BRBookingGuest", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", "Booking")
                        .WithMany("BRBookingGuests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", "Guest")
                        .WithMany("BRBookingGuests")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Payment", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Staff", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", "Hotel")
                        .WithMany("Staffs")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.Navigation("BRBookingGuests");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", b =>
                {
                    b.Navigation("BRBookingGuests");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
