// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YB_MelihEfeOmer_RezervasyonApp.DataAccess.Context;

#nullable disable

namespace YB_MelihEfeOmer_RezervasyonApp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.BRBookingGuest", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId", "GuestId");

                    b.HasIndex("GuestId");

                    b.ToTable("BRBookingGuests");

                    b.HasData(
                        new
                        {
                            BookingId = new Guid("1605fc67-d031-4e54-b872-53bcabde7543"),
                            GuestId = new Guid("f9cce1c4-cd5c-4ec5-a37d-5e8c3d41c5d6"),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4353),
                            IsActive = false,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookingId = new Guid("29690c18-f14b-4235-944b-05660631475f"),
                            GuestId = new Guid("f9cce1c4-cd5c-4ec5-a37d-5e8c3d41c5d6"),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4377),
                            IsActive = false,
                            IsDeleted = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CheckinDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckoutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1605fc67-d031-4e54-b872-53bcabde7543"),
                            CheckinDate = new DateOnly(2024, 7, 23),
                            CheckoutDate = new DateOnly(2024, 7, 28),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4286),
                            IsActive = false,
                            IsDeleted = false,
                            RoomId = new Guid("3900fda2-7190-486a-b525-c0ebddefd668"),
                            TotalPrice = 0m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("29690c18-f14b-4235-944b-05660631475f"),
                            CheckinDate = new DateOnly(2024, 8, 1),
                            CheckoutDate = new DateOnly(2024, 8, 2),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4316),
                            IsActive = false,
                            IsDeleted = false,
                            RoomId = new Guid("3900fda2-7190-486a-b525-c0ebddefd668"),
                            TotalPrice = 0m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber")
                        .IsUnique()
                        .HasFilter("[IdentityNumber] IS NOT NULL");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9cce1c4-cd5c-4ec5-a37d-5e8c3d41c5d6"),
                            Address = "aa",
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4247),
                            DateOfBirth = new DateOnly(1999, 9, 9),
                            Email = "aaa",
                            FirstName = "Test",
                            IdentityNumber = "11111111111",
                            IsActive = false,
                            IsDeleted = false,
                            LastName = "Test",
                            Phone = "5656",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly>("CheckinTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckoutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("Stars")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab82cf27-2085-4fd1-b0c4-00247dc3e6ef"),
                            Address = "İzmir/Alsancak",
                            CheckinTime = new TimeOnly(8, 0, 0),
                            CheckoutTime = new TimeOnly(23, 59, 0),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(3786),
                            Email = "ibishotel@hotmail.com",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "İbis",
                            Phone = "09998887766",
                            Stars = (byte)4,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("94525f48-c2d7-40df-9eb1-05e497a3b017"),
                            Address = "İstanbul/Eminönü",
                            CheckinTime = new TimeOnly(8, 0, 0),
                            CheckoutTime = new TimeOnly(23, 59, 0),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(3866),
                            Email = "turkuaz@hotmail.com",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Turkuaz",
                            Phone = "55554443265",
                            Stars = (byte)4,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3900fda2-7190-486a-b525-c0ebddefd668"),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4104),
                            HotelId = new Guid("ab82cf27-2085-4fd1-b0c4-00247dc3e6ef"),
                            IsActive = false,
                            IsDeleted = false,
                            RoomNumber = 101,
                            RoomTypeId = new Guid("c5f47aa4-c21a-4c9b-be83-d914f209f970"),
                            Status = "Avaliable",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ffc4d23e-c4f8-4d45-b50a-61821f738a86"),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4131),
                            HotelId = new Guid("ab82cf27-2085-4fd1-b0c4-00247dc3e6ef"),
                            IsActive = false,
                            IsDeleted = false,
                            RoomNumber = 102,
                            RoomTypeId = new Guid("c5f47aa4-c21a-4c9b-be83-d914f209f970"),
                            Status = "Avaliable",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6d1a079d-8ba5-4ad4-bf19-749e193a7d0b"),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4151),
                            HotelId = new Guid("ab82cf27-2085-4fd1-b0c4-00247dc3e6ef"),
                            IsActive = false,
                            IsDeleted = false,
                            RoomNumber = 201,
                            RoomTypeId = new Guid("c82931f9-eb9c-4a13-a7d5-010d403dee55"),
                            Status = "Avaliable",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d51aa5ff-b10d-458c-9827-44ba21715588"),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4174),
                            HotelId = new Guid("ab82cf27-2085-4fd1-b0c4-00247dc3e6ef"),
                            IsActive = false,
                            IsDeleted = false,
                            RoomNumber = 202,
                            RoomTypeId = new Guid("4526b32f-357a-4840-83bf-c623eb165b16"),
                            Status = "Avaliable",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1015a3ab-0203-4c78-a5f8-074565d28159"),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4194),
                            HotelId = new Guid("94525f48-c2d7-40df-9eb1-05e497a3b017"),
                            IsActive = false,
                            IsDeleted = false,
                            RoomNumber = 101,
                            RoomTypeId = new Guid("4526b32f-357a-4840-83bf-c623eb165b16"),
                            Status = "Avaliable",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("98b44101-d5d1-4f37-9773-21dc715502bd"),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4219),
                            HotelId = new Guid("94525f48-c2d7-40df-9eb1-05e497a3b017"),
                            IsActive = false,
                            IsDeleted = false,
                            RoomNumber = 102,
                            RoomTypeId = new Guid("4526b32f-357a-4840-83bf-c623eb165b16"),
                            Status = "Avaliable",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Capacity")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5f47aa4-c21a-4c9b-be83-d914f209f970"),
                            Capacity = (byte)2,
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4017),
                            Description = "Suit type room",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Suit",
                            PricePerNight = 1000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c82931f9-eb9c-4a13-a7d5-010d403dee55"),
                            Capacity = (byte)4,
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4052),
                            Description = "King type room",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "King",
                            PricePerNight = 4000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4526b32f-357a-4840-83bf-c623eb165b16"),
                            Capacity = (byte)1,
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(4076),
                            Description = "Single type room",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Single",
                            PricePerNight = 500m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6e9838f-673b-449e-a4da-121ccc4bad37"),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(3920),
                            DateOfBirth = new DateOnly(1970, 1, 1),
                            Email = "ThisIsStaff@hotmail.com",
                            FirstName = "Ali",
                            HireDate = new DateOnly(2010, 1, 1),
                            HotelId = new Guid("ab82cf27-2085-4fd1-b0c4-00247dc3e6ef"),
                            IsActive = false,
                            IsDeleted = false,
                            LastName = "Vali",
                            Phone = "09995554433",
                            Position = "Manager",
                            Salary = 50000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b93f68d3-b1ec-4bf9-b5f9-a2ef58b2c386"),
                            CreatedTime = new DateTime(2024, 7, 24, 21, 35, 46, 641, DateTimeKind.Local).AddTicks(3976),
                            DateOfBirth = new DateOnly(1980, 1, 1),
                            Email = "ThisIsStaff2@hotmail.com",
                            FirstName = "Murat",
                            HireDate = new DateOnly(1981, 1, 1),
                            HotelId = new Guid("94525f48-c2d7-40df-9eb1-05e497a3b017"),
                            IsActive = false,
                            IsDeleted = false,
                            LastName = "Duran",
                            Phone = "09995554433",
                            Position = "Manager",
                            Salary = 50000m,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.BRBookingGuest", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", "Booking")
                        .WithMany("BRBookingGuests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", "Guest")
                        .WithMany("BRBookingGuests")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Payment", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Staff", b =>
                {
                    b.HasOne("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", "Hotel")
                        .WithMany("Staffs")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Booking", b =>
                {
                    b.Navigation("BRBookingGuests");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Guest", b =>
                {
                    b.Navigation("BRBookingGuests");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("YB_MelihEfeOmer_RezervasyonApp.Entity.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
